### ISSUE TITLE
How to run demo with keywords "hi wenwen"

### ISSUE THREAD

**Issue by dragen1860** [wenet-e2e/wenet-kws#5]
Dear author:
   I noticed you have published the pretrained "hey wenwen" checkpoints. But I dont know how  to play with your pretrained models. Could you kindly give some simple guides on it? thank you very much.

**Comment by jingyonghou** [comment]
> Dear author: I noticed you have published the pretrained "hey wenwen" checkpoints. But I dont know how to play with your pretrained models. Could you kindly give some simple guides on it? thank you very much.

Thanks for paying attention to our work. The demo code is not finished yet, we are still hardly working on it.
